theme: jekyll-theme-cayman
title: Enchantment in the History of Capitalism
description: We're a network of scholars interested in enchantment in the history of capitalism. Join us in our roundtables.
